---

vars:
  HostIp: "{{ ansible_env.HOST_EXTERNAL_IPV4 }}"

- name: Build config file for caddy
  template:
    src: "Caddyfile.hcl.j2"
    dest: "/etc/caddy/Caddyfile"

- name: Copy Caddyfile contents
  shell: "cat /etc/caddy/Caddyfile"
  register: internal_caddyfile_contents

- name: Assign Caddyfile contents to environment variable
  environment:
    INTERNAL_CADDYFILE_CONTENTS: "{{ internal_caddyfile_contents.stdout }}"
