---

- name: Create directory for the nomad jobs
  file:
    path: "{{ nomad_jobs_path }}"
    state: directory
    recurse: yes

- name: Build config files for the nomad jobs
  vars:
    DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
    BaseDomain: "{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"

  block:
    - name: Initiate config file building for MySQL
      include: configure.yml
      vars:
        service: "mysql"
        DatabaseRootPassword: "{{ lookup('bitwarden', 'homelab/secrets/mysql/root_password') }}"

    - name: Initiate config file building for redis
      include: configure.yml
      vars:
        service: "redis"

    - name: Initiate config file building for Firefly-III
      include: configure.yml
      vars:
        service: "firefly"
        FireflyApplicationEncryptionKey: "{{ lookup('community.general.random_string', special=false, length=32) }}"
        FireflyDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/firefly/username') }}"
        FireflyDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/firefly/password') }}"
        FireflyDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/firefly/database') }}"
        MapboxApiToken: "{{ lookup('bitwarden', 'homelab/secrets/firefly/mapboxtoken') }}"

    - name: Initiate config file building for Bookstack
      include: configure.yml
      vars:
        service: "bookstack"
        BookstackDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/username') }}"
        BookstackDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/password') }}"
        BookstackDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/database') }}"

    - name: Initiate config file building for Vikunja
      include: configure.yml
      vars:
        service: "vikunja"
        VikunjaDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/username') }}"
        VikunjaDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/password') }}"
        VikunjaDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/database') }}"
        VikunjaMailerHost: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/host') }}"
        VikunjaMailerPort: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/port') }}"
        VikunjaMailerUsername: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/username') }}"
        VikunjaMailerPassword: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/password') }}"
        VikunjaMailerSender: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/sender') }}"
        VikunjaJwtSecret: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/jwt/secret') }}"

    - name: Initiate config file building for Nextcloud
      include: configure.yml
      vars:
        service: "nextcloud"
        NextcloudDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/username') }}"
        NextcloudDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/password') }}"
        NextcloudDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/database') }}"
        NextcloudRedisHost: "{{ HOST_EXTERNAL_IPV4 }}"
        NextcloudRedisPort: "6379"

    - name: Initiate config file building for Webtrees
      include: configure.yml
      vars:
        service: "webtrees"
        WebtreesDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/username') }}"
        WebtreesDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/password') }}"
        WebtreesDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/database') }}"

    - name: Initiate config file building for Photoprism
      include: configure.yml
      vars:
        service: "photoprism"
        PhotoprismDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/username') }}"
        PhotoprismDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/password') }}"
        PhotoprismDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/database') }}"
        PhotoprismAdminPassword: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/admin_password') }}"

    - name: Initiate config file building for AINV
      include: configure.yml
      vars:
        service: "ainv"
        AinvDevDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/username') }}"
        AinvDevDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/password') }}"
        AinvDevDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/database') }}"
        AinvProdDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/username') }}"
        AinvProdDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/password') }}"
        AinvProdDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/database') }}"

    - name: Initiate config file building for audiobookshelf
      include: configure.yml
      vars:
        service: "audiobookshelf"

    - name: Initiate config file building for duplicati
      include: configure.yml
      vars:
        service: "duplicati"

    - name: Initiate config file building for ntfy
      include: configure.yml
      vars:
        service: "ntfy"

    - name: Initiate config file building for cronicle
      include: configure.yml
      vars:
        service: "cronicle"

    - name: Initiate config file building for metabase
      include: configure.yml
      vars:
        service: "metabase"
        MetabaseDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/metabase/username') }}"
        MetabaseDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/metabase/password') }}"
        MetabaseDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/metabase/database') }}"
        MetabaseDatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
        MetabaseEncryptionKey: "{{ lookup('bitwarden', 'homelab/secrets/metabase/encryption/key') }}"

    - name: Initiate config file building for n8n
      include: configure.yml
      vars:
        service: "n8n"
        N8NDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/n8n/username') }}"
        N8NDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/n8n/password') }}"
        N8NDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/n8n/database') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"

    - name: Initiate config file building for kavita
      include: configure.yml
      vars:
        service: "kavita"

    - name: Initiate config file building for mailpile
      include: configure.yml
      vars:
        service: "mailpile"

    - name: Initiate config file building for miniflux
      include: configure.yml
      vars:
        service: "miniflux"
        DatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/miniflux/postgres/username') }}"
        DatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/miniflux/postgres/password') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
        MinifluxUsername: "{{ lookup('bitwarden', 'homelab/secrets/miniflux/username') }}"
        MinifluxPassword: "{{ lookup('bitwarden', 'homelab/secrets/miniflux/password') }}"

    - name: Initiate config file building for souptik
      include: configure.yml
      vars:
        service: "souptik"
        SouptikDatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/souptik/username') }}"
        SouptikDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/souptik/password') }}"
        SouptikDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/souptik/database') }}"
        SouptikDebugLog: "{{ lookup('bitwarden', 'homelab/secrets/souptik/debug') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"

    - name: Initiate config file building for PostgreSQL
      include: configure.yml
      vars:
        service: "postgresql"
        DatabaseRootUser: "{{ lookup('bitwarden', 'homelab/secrets/postgresql/root_user') }}"
        DatabaseRootPassword: "{{ lookup('bitwarden', 'homelab/secrets/postgresql/root_password') }}"

    - name: Initiate config file building for Monica
      include: configure.yml
      vars:
        service: "monica"
        AppKey: "{{ lookup('bitwarden', 'homelab/secrets/monica/appkey') }}"
        DatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/monica/username') }}"
        DatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/monica/password') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"

    - name: Initiate config file building for Servarr
      include: configure.yml
      vars:
        service: "servarr"

    - name: Initiate config file building for AOPS
      include: configure.yml
      vars:
        service: "aops"
        FbApiKey: "{{ lookup('bitwarden', 'homelab/secrets/aops/fb/apikey') }}"
        FbAuthDomain: "{{ lookup('bitwarden', 'homelab/secrets/aops/fb/authdomain') }}"
        FbBucket: "{{ lookup('bitwarden', 'homelab/secrets/aops/fb/bucket') }}"
        FbDbUrl: "{{ lookup('bitwarden', 'homelab/secrets/aops/fb/dburl') }}"
        EmailRecipient1: "{{ lookup('bitwarden', 'homelab/secrets/aops/emailrec1') }}"
        EmailRecipient2: "{{ lookup('bitwarden', 'homelab/secrets/aops/emailrec2') }}"
        Secret: "{{ lookup('bitwarden', 'homelab/secrets/aops/fb/secret') }}"
        YMail: "{{ lookup('bitwarden', 'homelab/secrets/aops/ymail') }}"
        YPassword: "{{ lookup('bitwarden', 'homelab/secrets/aops/ypassword') }}"

    - name: Initiate config file building for Immich
      include: configure.yml
      vars:
        service: "immich"
        Hostname: "{{ HOST_EXTERNAL_IPV4 }}"
        ImmichUsername: "{{ lookup('bitwarden', 'homelab/secrets/immich/database/username') }}"
        ImmichPassword: "{{ lookup('bitwarden', 'homelab/secrets/immich/database/password') }}"
        ImmichDatabase: "{{ lookup('bitwarden', 'homelab/secrets/immich/database/database') }}"
        RedisHostname: "{{ HOST_EXTERNAL_IPV4 }}"
        ImmichJwtSecret: "{{ lookup('bitwarden', 'homelab/secrets/immich/jwt/secret') }}"
        TypesenseAPIKey: "{{ lookup('bitwarden', 'homelab/secrets/immich/typesense/apikey') }}"

    - name: Initiate config file building for snibox
      include: configure.yml
      vars:
        service: "snibox"
        SecretKeyBase: "{{ lookup('bitwarden', 'homelab/secrets/snibox/secret_key_base') }}"

    - name: Initiate config file building for Bitwarden backup
      include: configure.yml
      vars:
        service: "bitwarden_backup"
        BitwardenUserName: "{{ lookup('bitwarden', 'homelab/secrets/bitwarden/username') }}"
        BitwardenPassword: "{{ lookup('bitwarden', 'homelab/secrets/bitwarden/password') }}"
        BitwardenBackupArchivePassword: "{{ lookup('bitwarden', 'homelab/secrets/bitwarden/archive/password') }}"
        BitwardenClientId: "{{ lookup('bitwarden', 'homelab/secrets/bitwarden/clientid') }}"
        BitwardenClientSecret: "{{ lookup('bitwarden', 'homelab/secrets/bitwarden/clientsecret') }}"

    - name: Initiate config file building for MongoDB
      include: configure.yml
      vars:
        service: "mongodb"

    - name: Initiate config file building for YourSpotify
      include: configure.yml
      vars:
        service: "your_spotify"
        SpotifyPublicKey: "{{ lookup('bitwarden', 'homelab/secrets/spotify/publickey') }}"
        SpotifySecretKey: "{{ lookup('bitwarden', 'homelab/secrets/spotify/secretkey') }}"

    - name: Initiate config file building for memoet
      include: configure.yml
      vars:
        service: "memoet"
        DatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/memoet/postgres/username') }}"
        DatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/memoet/postgres/password') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
        SecretKeyBase: "{{ lookup('bitwarden', 'homelab/secrets/memoet/secret') }}"

    - name: Initiate config file building for smepl
      include: configure.yml
      vars:
        service: "smepl"
        smeplDatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/smepl/username') }}"
        smeplDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/smepl/password') }}"
        smeplDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/smepl/database') }}"
        smeplDebugLog: "{{ lookup('bitwarden', 'homelab/secrets/smepl/debug') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"

    - name: Initiate config file building for xcuzme
      include: configure.yml
      vars:
        service: "xcuzme"
        DatabaseRootUser: "{{ lookup('bitwarden', 'homelab/secrets/postgresql/root_user') }}"
        DatabaseRootPassword: "{{ lookup('bitwarden', 'homelab/secrets/postgresql/root_password') }}"
        DatabaseUser: "{{ lookup('bitwarden', 'homelab/secrets/xcuzme/username') }}"
        DatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/xcuzme/password') }}"
        DatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/xcuzme/dbname') }}"
        OpenAIOrg: "{{ lookup('bitwarden', 'homelab/secrets/xcuzme/openai/org') }}"
        OpenAIAPIKey: "{{ lookup('bitwarden', 'homelab/secrets/xcuzme/openai/key') }}"
        DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"

    - name: Initiate config file building for Watchtower
      include: configure.yml
      vars:
        service: "watchtower"

    - name: Initiate config file building for mind
      include: configure.yml
      vars:
        service: "mind"

    - name: Initiate config file building for Chat-With-GPT
      include: configure.yml
      vars:
        service: "chatgpt"

- name: Install the required apt packages
  apt:
    name:
      - python3-pip

- name: Install python-nomad library
  pip:
    name:
      - python-nomad
    executable: pip3

- name: Launch the nomad jobs
  include: launch.yml
  vars:
    DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
    service: "{{ item }}"
  with_items:
    - mysql
    - postgresql
    - redis
    - firefly
    - bookstack
    - vikunja
    - nextcloud
    - webtrees
    - audiobookshelf
    - duplicati
    - ntfy
    - cronicle
    - miniflux
    - souptik
    - monica
    - servarr
    - immich
    - snibox
    - bitwarden_backup
    - mongodb
    - your_spotify
    - memoet
    - smepl
    - chatgpt
    - xcuzme
