---

- name: Create directory for the nomad jobs
  file:
    path: "{{ nomad_jobs_path }}"
    state: directory
    recurse: yes

- name: Build config files for the nomad jobs
  vars:
    DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
    BaseDomain: "{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"

  block:
    - name: Initiate config file building for MySQL
      include: configure.yml
      vars:
        service: "mysql"
        DatabaseRootPassword: "{{ lookup('bitwarden', 'homelab/secrets/mysql/root_password') }}"

    - name: Initiate config file building for redis
      include: configure.yml
      vars:
        service: "redis"

    - name: Initiate config file building for Firefly-III
      include: configure.yml
      vars:
        service: "firefly"
        FireflyApplicationEncryptionKey: "{{ lookup('community.general.random_string', special=false, length=32) }}"
        FireflyDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/firefly/username') }}"
        FireflyDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/firefly/password') }}"
        FireflyDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/firefly/database') }}"

    - name: Initiate config file building for Bookstack
      include: configure.yml
      vars:
        service: "bookstack"
        BookstackDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/username') }}"
        BookstackDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/password') }}"
        BookstackDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/bookstack/database') }}"

    - name: Initiate config file building for Vikunja
      include: configure.yml
      vars:
        service: "vikunja"
        VikunjaDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/username') }}"
        VikunjaDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/password') }}"
        VikunjaDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/database') }}"
        VikunjaMailerHost: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/host') }}"
        VikunjaMailerPort: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/port') }}"
        VikunjaMailerUsername: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/username') }}"
        VikunjaMailerPassword: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/password') }}"
        VikunjaMailerSender: "{{ lookup('bitwarden', 'homelab/secrets/vikunja/mailer/sender') }}"

    - name: Initiate config file building for Nextcloud
      include: configure.yml
      vars:
        service: "nextcloud"
        NextcloudDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/username') }}"
        NextcloudDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/password') }}"
        NextcloudDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/nextcloud/database') }}"
        NextcloudRedisHost: "{{ HOST_EXTERNAL_IPV4 }}"
        NextcloudRedisPort: "6379"

    - name: Initiate config file building for Webtrees
      include: configure.yml
      vars:
        service: "webtrees"
        WebtreesDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/username') }}"
        WebtreesDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/password') }}"
        WebtreesDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/webtrees/database') }}"

    - name: Initiate config file building for Photoprism
      include: configure.yml
      vars:
        service: "photoprism"
        PhotoprismDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/username') }}"
        PhotoprismDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/password') }}"
        PhotoprismDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/database') }}"
        PhotoprismAdminPassword: "{{ lookup('bitwarden', 'homelab/secrets/photoprism/admin_password') }}"

    - name: Initiate config file building for AINV
      include: configure.yml
      vars:
        service: "ainv"
        AinvDevDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/username') }}"
        AinvDevDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/password') }}"
        AinvDevDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/ainv/dev/database') }}"
        AinvProdDatabaseUsername: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/username') }}"
        AinvProdDatabasePassword: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/password') }}"
        AinvProdDatabaseName: "{{ lookup('bitwarden', 'homelab/secrets/ainv/prod/database') }}"

    - name: Initiate config file building for audiobookshelf
      include: configure.yml
      vars:
        service: "audiobookshelf"

    - name: Initiate config file building for duplicati
      include: configure.yml
      vars:
        service: "duplicati"

    - name: Initiate config file building for ntfy
      include: configure.yml
      vars:
        service: "ntfy"

- name: Install the required apt packages
  apt:
    name:
      - python3-pip

- name: Install python-nomad library
  pip:
    name:
      - python-nomad
    executable: pip3

- name: Launch the nomad jobs
  include: launch.yml
  vars:
    DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
    service: "{{ item }}"
  with_items:
    - mysql
    - redis
    - firefly
    - bookstack
    - vikunja
    - nextcloud
    - webtrees
    - photoprism
    - ainv
    - audiobookshelf
    - duplicati
    - ntfy
