{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    {{- include "itineris.adminLabels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "itineris.adminSelectorLabels" . | nindent 4 }}
{{- end }}
