---

- name: Prepare local
  hosts: localhost
  roles:
    - role: ansible-modules-bitwarden
    - role: setup-cloudflared-credentials
      tags:
        - config

- name: Set up homelab
  hosts: homelab
  vars_files:
          - config.yml
  roles:
    - role: ansible-modules-bitwarden

    - role: launch-orchestrators
      tags:
        - config
        - orchestration

    - role: launch-nomad-jobs
      tags:
        - config
        - service

    - role: caddy_ansible.caddy_ansible
      caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
      vars:
        HostIp: "{{ HOST_EXTERNAL_IPV4 }}"
      tags:
        - service
        - gateway

    - role: setup-binaries
      tags:
        - config

    - role: papanito.cloudflared
      caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
      vars:
        cf_systemd_user: root
        cf_systemd_group: root
        cf_cert_location: ~/.secrets/cert.pem
      cf_tunnels:
        dietpigw:
          tunnel_id: "{{ lookup('bitwarden', 'homelab/secrets/cloudflare/tunnels/1/tunnel_id') }}"
          credentials-file: /etc/cloudflared/{{ lookup('bitwarden', 'homelab/secrets/cloudflare/tunnels/1/tunnel_id') }}.json
          account_tag: "{{ lookup('bitwarden', 'homelab/secrets/cloudflare/tunnels/1/account_tag') }}"
          tunnel_secret: "{{ lookup('bitwarden', 'homelab/secrets/cloudflare/tunnels/1/tunnel_secret') }}"
          loglevel: debug
          routes:
            dns:
            - "firefly"
            - "bookstack"
            - "vikunja"
            - "nextcloud"
            - "webtrees"
            - "photoprism"
            - "ainv-dev"
            - "ainv"
            - "audiobookshelf"
            - "duplicati"
            - "ntfy"
            - "cronicle"
            - "metabase"
            - "n8n"
            - "kavita"
            - "mailpile"
            - "miniflux"
          ingress:
          - hostname: "firefly.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8081
          - hostname: "bookstack.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8082
          - hostname: "vikunja.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8083
          - hostname: "nextcloud.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8084
          - hostname: "webtrees.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8085
          - hostname: "photoprism.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8086
          - hostname: "ainv-dev.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8087
          - hostname: "ainv.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8088
          - hostname: "audiobookshelf.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8090
          - hostname: "duplicati.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8091
          - hostname: "ntfy.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8092
          - hostname: "cronicle.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8093
          - hostname: "metabase.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8094
          - hostname: "n8n.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8095
          - hostname: "kavita.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8096
          - hostname: "mailpile.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8097
          - hostname: "miniflux.{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"
            service: http://localhost:8098
          - service: http_status:404
      tags:
        - networking
