---

roles:
- name: caddy_ansible.caddy_ansible
  src: https://github.com/caddy-ansible/caddy-ansible.git
  version: origin/master

- name: papanito.cloudflared
  src: https://github.com/papanito/ansible-role-cloudflared.git
  version: origin/main

- name: ansible-modules-bitwarden
  src: https://github.com/c0sco/ansible-modules-bitwarden
  version: origin/master

collections:
- name: community.mysql
- name: ansible.posix
- name: community.general
