---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-config-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-data-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye
  namespace: apps
  labels:
    app: motioneye
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 12h"
    keel.sh/approvals: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: motioneye
  template:
    metadata:
      labels:
        app: motioneye
    spec:
      containers:
      - name: motioneye
        image: ccrisan/motioneye:master-amd64
        ports:
        - containerPort: 8765
          name: http
        env:
        - name: TZ
          value: "Asia/Kolkata"
        volumeMounts:
        - name: config
          mountPath: /etc/motioneye
        - name: data
          mountPath: /var/lib/motioneye
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: motioneye-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: motioneye-data-pvc
