---

- name: Set up rclone and start regular backup cron job
  vars:
    Name: "{{ lookup('bitwarden', 'homelab/secrets/backup/name') }}"
    Account: "{{ lookup('bitwarden', 'homelab/secrets/backup/account') }}"
    Key: "{{ lookup('bitwarden', 'homelab/secrets/backup/key') }}"
    Bucket: "{{ lookup('bitwarden', 'homelab/secrets/backup/bucket') }}"
  block:
    - name: Create rclone config directory
      file:
        path: "~/.config/rclone"
        state: directory
        recurse: yes

    - name: Build rclone config
      template:
        src: rclone.conf.j2
        dest: "~/.config/rclone/rclone.conf"

    - name: Install rclone package
      shell: "curl https://rclone.org/install.sh | bash"
      ignore_errors: true

    - name: Start files backup cron job
      ansible.builtin.cron:
        name: "homelab_b2_backup"
        minute: "30"
        hour: "4"
        job: "rclone bisync -v --resync {{ hdd_mount_path }}/homelab {{ Name }}:{{ Bucket }}/backup/homelab"
