---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: ntfy
    repo: https://helm-charts.rm3l.org
    version: 0.1.1
    releaseName: ntfy
    namespace: apps
    valuesFile: values.yaml
    # Don't render the chart's `tests/` (helm hook test pod that wgets the service)
    skipTests: true

resources:
  - ingress.yaml
