apiVersion: v1
appVersion: 0.19.1
description: Open source, tool for automating Kubernetes deployment updates. This
  is a custom fork of the original Keel project.
engine: gotpl
home: https://clem59170.github.io/keel
icon: https://raw.githubusercontent.com/keel-hq/keel/master/static/keel-logo.png
keywords:
- kubernetes deployment
- helm release
- continuous deployment
maintainers:
- name: clem59170
name: keel
sources:
- https://github.com/keel-hq/keel
- https://github.com/clem59170/keel
version: 1.0.5
