annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/linuxserver/bookstack docker tag to version-v24.12.1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/BookStackApp/BookStack
    - name: Container Source
      url: https://github.com/linuxserver/docker-bookstack
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/bookstack
apiVersion: v2
appVersion: version-v24.12.1
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 20.1.1
description: A simple, self-hosted, easy-to-use platform for organising and storing
  information.
home: https://charts.gabe565.com/charts/bookstack/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/bookstack/icon.svg
keywords:
- bookstack
- wiki
- documentation
kubeVersion: '>=1.22.0-0'
name: bookstack
sources:
- https://github.com/BookStackApp/BookStack
- https://github.com/linuxserver/docker-bookstack
type: application
version: 0.20.0
