---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: texas-fold-em
    repo: oci://ghcr.io/rounakdatta/charts
    version: 0.4.0_755b538
    releaseName: texas-fold-em
    namespace: apps
    valuesFile: values.yaml

resources:
  - ingress.yaml
