--- 

- name: Create directory for {{ service }}
  file:
    path: "/etc/{{ service }}.d"
    state: directory
    recurse: yes

- name: Build config file for {{ service }}
  template:
    src: "{{ service }}.hcl.j2"
    dest: "/etc/{{ service }}.d/{{ service }}.hcl"

- name: Build systemd file for {{ service }}
  template:
    src: "{{ service }}.service.j2"
    dest: "/etc/systemd/system/{{ service }}.service"

- name: Run {{ service }}
  ansible.builtin.systemd:
    state: reloaded
    name: "{{ service }}"

- name: Run {{ service }}
  ansible.builtin.systemd:
    state: restarted
    name: "{{ service }}"
