---

- name: Install docker
  shell: "curl -X GET https://get.docker.com/ | sh"

- name: Download nomad package
  get_url:
    url: "https://releases.hashicorp.com/nomad/1.3.5/nomad_1.3.5_linux_{{ install_arch }}.zip"
    dest: "/tmp/"

- name: Install the required apt packages
  apt:
    name:
      - unzip

- name: Inflate the package
  ansible.builtin.unarchive:
    src: "/tmp/nomad_1.3.5_linux_{{ install_arch }}.zip"
    dest: "/usr/bin"
    remote_src: yes

- name: Create mount directory for mysql
  file:
    path: "{{ hdd_mount_path }}/homelab/mysql"
    state: directory
    recurse: yes

- name: Create mount directory for nextcloud
  file:
    path: "{{ hdd_mount_path }}/homelab/nextcloud"
    state: directory
    recurse: yes

- name: launch systemd services
  include: configure.yml
  vars:
    HostIp: "{{ HOST_EXTERNAL_IPV4 }}"
    service: "{{ item }}"
    relative_path_to_books: "{{ lookup('bitwarden', 'homelab/secrets/kavita/books/path') }}"
  with_items:
    - nomad
