---

- name: Install docker
  shell: "curl -X GET https://get.docker.com/ | sh"

- name: Download nomad package
  get_url:
    url: "https://releases.hashicorp.com/nomad/1.3.1/nomad_1.3.1_linux_{{ install_arch }}.zip"
    dest: "/tmp/"

- name: Install the required apt packages
  apt:
    name:
      - unzip

- name: Inflate the package
  ansible.builtin.unarchive:
    src: "/tmp/nomad_1.3.1_linux_{{ install_arch }}.zip"
    dest: "/usr/bin"
    remote_src: yes

- name: Create mount directory for mysql
  file:
    path: "{{ hdd_mount_path }}/homelab/mysql"
    state: directory
    recurse: yes

- name: Create mount directory for nextcloud
  file:
    path: "{{ hdd_mount_path }}/homelab/nextcloud"
    state: directory
    recurse: yes

- name: Set up flyctl (connecting to an external database)
  vars:
    DatabaseHost: "{{ HOST_EXTERNAL_IPV4 }}"
    BaseDomain: "{{ lookup('bitwarden', 'homelab/secrets/domain/public/base') }}"

  block:
    - name: Install flyctl
      shell: "curl -L https://fly.io/install.sh | sh"

    - name: Set up flyctl PG proxy
      environment:
        FLY_ACCESS_TOKEN: "{{ lookup('bitwarden', 'homelab/secrets/fly.io/token') }}"
      shell: "/.fly/bin/flyctl proxy 5432 -a {{ lookup('bitwarden', 'homelab/secrets/fly.io/postgres/name') }}"

- name: launch systemd services
  include: configure.yml
  vars:
    HostIp: "{{ HOST_EXTERNAL_IPV4 }}"
    service: "{{ item }}"
    relative_path_to_books: "{{ lookup('bitwarden', 'homelab/secrets/kavita/books/path') }}"
  with_items:
    - nomad
