---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes
    version: 1.9.13
    releaseName: firefly
    namespace: apps
    valuesFile: values.yaml

resources:
  - ingress.yaml
