apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lezepplean.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8787
      protocol: TCP
  selector:
    {{- include "lezepplean.selectorLabels" . | nindent 4 }}
