---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: synt
    repo: oci://ghcr.io/rounakdatta/charts
    version: 0.2.1
    releaseName: synt
    namespace: apps
    valuesFile: values.yaml

resources:
  - ingress.yaml
