---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tinyauth

helmCharts:
  - name: tinyauth
    repo: https://helm.tinyauth.app
    version: 2.0.8
    releaseName: tinyauth
    namespace: tinyauth
    valuesFile: values.yaml

resources:
  - namespace.yaml
  # secret tinyauth-credentials is synced from Bitwarden by ansible
  - middleware.yaml
  - ingress.yaml
