annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to Webtrees v2.1.26
apiVersion: v2
appVersion: 2.1.26
dependencies:
- name: common
  repository: http://bjw-s-labs.github.io/helm-charts/
  version: 0.2.0
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: ~18
description: Open-source online collaborative genealogy application
home: https://github.com/djjudas21/charts/tree/master/charts/webtrees
icon: https://raw.githubusercontent.com/fisharebest/webtrees/main/resources/img/webtrees-icon.png
keywords:
- webtrees
- genealogy
- family-tree
- ancestry
kubeVersion: '>=1.16.0-0'
maintainers:
- email: djjudas21@users.noreply.github.com
  name: djjudas21
name: webtrees
sources:
- https://github.com/fisharebest/webtrees
- https://github.com/NathanVaughn/webtrees-docker
version: 2.2.23
